# NumPy Basics

1. Review를 위한 단계
- 방식 : chapter04 장을 보면서 이해하고 주석 달기
- 제출 방식 : 강사가 제시한 폴더에 파일명 수정해서 제출하
- 파일명 : **step05_bookReview임동원.ipynb**

In [2]:
import numpy as np

## The NumPy ndarray: A Multidimensional Array Object

In [3]:
data = np.random.randn(2, 3) #랜덤으로 2*3 행렬의 배열을 만든다.
data

array([[-0.97885847, -0.50156506, -0.6020886 ],
       [-0.24183852, -0.12173015, -0.31682911]])

In [5]:
print(data * 10) 
print(data + data) # 각성분 끼리의 합

[[-9.78858465 -5.01565062 -6.02088603]
 [-2.4183852  -1.2173015  -3.16829114]]
[[-1.95771693 -1.00313012 -1.20417721]
 [-0.48367704 -0.2434603  -0.63365823]]


In [7]:
data.shape
data.dtype#data행렬의 데이터타입(자료형)

dtype('float64')

In [8]:
data.shape #data행렬의 구조

(2, 3)

### Creating ndarrays

In [11]:
#array함수를 이용하여 배열생성-순차적인 객체를 받아 넘겨받은 데이터가 들어있는 새로운 NumPy배열을 생성.
data1 = [6, 7.5, 8, 0, 1] 
arr1 = np.array(data1) # 배열을 넘겨받아 새로운 numpy배열을 생성
arr1 # 7.5에 맞춰 다른 값까지 float타입으로 출력됨

array([6. , 7.5, 8. , 0. , 1. ])

In [14]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]] # 같은길이의 리스트가 담겨 있는 순차데이터는 다차원 배열로 변환이 가능
arr2 = np.array(data2)
arr2 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
arr2.ndim
arr2.shape 

(2, 4)

In [16]:
arr2.ndim #dimension : 2차원

2

In [21]:
arr1.dtype

dtype('float64')

In [20]:
arr2.dtype # np.array는 생성될때 적절한 자료형을 추정한다.

dtype('int32')

In [30]:
np.zeros(10) # 1*10 형태의 배열 생성

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.zeros((3, 6)) # 3*6형태의 배열 생성

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [32]:
np.arange(15) #arange: 파이썬 range의 배열버전

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays

In [33]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr1.dtype) # float64 : 배정밀도 부동소수점. C언어의 double형과 파이썬의 float객체와 호환
print(arr2.dtype)

float64
int32


In [39]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)

float_arr = arr.astype(np.float64)  # astype 메서드를 이용하여 배열의 dtype을 다른 형으로 명시적 변경
print(float_arr.dtype)                                                   # int -> float
print(float_arr)

int32
float64
[1. 2. 3. 4. 5.]


In [49]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr)
print(arr.astype(np.int32))

a=(arr.astype(np.int32))  # 정수형을 부동소수점으로 변환. 소수점아래자리가 버려짐
a.dtype

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]
[ 3 -1 -2  0 12 10]


dtype('int32')

In [60]:
int_array = np.arange(10)
print(int_array)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
print(calibers)
print(calibers.dtype)
print(int_array.astype(calibers.dtype)) #calibers의 자료형으로 변환되어 int_array가 정수형으로 변환

[0 1 2 3 4 5 6 7 8 9]
[0.22  0.27  0.357 0.38  0.44  0.5  ]
float64
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### Arithmetic with NumPy Arrays

**배열은 for반복문을 사용하지 않고 데이터를 일괄처리할 수 있기 때문에 중요하다.<br>
이를 벡터화라고 하는데, 같은 크기의 배열 간 산술연산은 배열의 각 요소 단위로 적용된다.**

In [62]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)
print(arr * arr)
print(arr - arr) 

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [66]:
1 / arr  # 스칼라값에 대한 산술산은 각 요소로 전달

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [67]:
arr ** 0.5 # 스칼라값에 대한 산술산은 각 요소로 전달

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [68]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print(arr2)
print(arr2 > arr)

[[ 0.  4.  1.]
 [ 7.  2. 12.]]
[[False  True False]
 [ True False  True]]


### Basic Indexing and Slicing

In [79]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
arr[5]


5

In [84]:
arr[5:8]

array([5, 6, 7])

In [85]:
arr[5:8] = 12
arr  # 12가 선택영역 전체로 전파. 

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [88]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [89]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [90]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

2차원배열

In [91]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2] # 각 색인에 해당하는 요소는 스칼라값이 아닌 1차원배열이 된다.

array([7, 8, 9])

In [92]:
arr2d[0][2] 
arr2d[0, 2]#서로 같은표현이다.

3

3차원배열

In [93]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [94]:
arr3d[0] # 3차원배열이므로 arr3d[0]는 2*3이 됨 

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
old_values = arr3d[0].copy() 
arr3d[0] = 42 # arr3d[0] 에는 스칼라값과 배열 모두 대입가능
print(arr3d)


arr3d[0] = old_values # 복사해두었던 원본데이터값 다시 넣어줌
print(arr3d)

[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [100]:
arr3d[1, 0] 

array([7, 8, 9])

In [99]:
arr3d[1,0,2]

9

In [101]:
x = arr3d[1]
print(x)
print(x[0])

[[ 7  8  9]
 [10 11 12]]
[7 8 9]


#### Indexing with slices(슬라이스 색인)

In [108]:
arr
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [110]:
print(arr2d)
print(arr2d[:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]


In [111]:
arr2d[:2, 1:] #여러개 색인으로 다차원슬라이싱

array([[2, 3],
       [5, 6]])

In [112]:
arr2d[1, :2]

array([4, 5])

In [113]:
arr2d[:2, 2]

array([3, 6])

In [114]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [115]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Boolean Indexing

In [129]:
names = np.array(['Bob', 'Joe', 'Bob', 'Will', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4) #7*4의 구조의 임의의 표준정규분포 데이터배열 생성

In [124]:
names # 중복된 이름이 포함된 배열 생성

array(['Bob', 'Joe', 'Bob', 'Will', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [130]:
data #7*4의 구조의 임의의 표준정규분포 데이터배열 생성

array([[-1.89780199, -0.49066266, -0.09391319,  0.90723345],
       [-2.2179903 , -0.50437655,  2.82136748, -1.22509817],
       [ 0.45400475,  0.38930527,  0.37473453, -0.28669946],
       [ 0.52686585,  1.26497721,  0.29905301,  0.81558314],
       [-0.5782994 , -0.86793028, -1.02028092, -1.35221332],
       [ 0.22808906, -1.30110567,  0.33990549,  1.26991028],
       [-1.72718357,  1.38626876, -0.43501871,  1.24760221]])

In [131]:
names == 'Bob' # 불리언 배열 반환

array([ True, False,  True, False, False, False, False])

In [132]:
data[names == 'Bob'] # 배열의 색인으로 사용 가능 

array([[-1.89780199, -0.49066266, -0.09391319,  0.90723345],
       [ 0.45400475,  0.38930527,  0.37473453, -0.28669946]])

In [133]:
print(data[names == 'Bob', 2:]) #각 행의 3번째 열부터 뽑음
print(data[names == 'Bob', 3]) # 4번째 열만 뽑음

[[-0.09391319  0.90723345]
 [ 0.37473453 -0.28669946]]
[ 0.90723345 -0.28669946]


In [134]:
mask = (names == 'Bob') | (names == 'Will') # 밥이거나 윌이거나
print(mask)
data[mask] # 밥이거나 윌이거나 인 위치 뽑기!

[ True False  True  True  True False False]


array([[-1.89780199, -0.49066266, -0.09391319,  0.90723345],
       [ 0.45400475,  0.38930527,  0.37473453, -0.28669946],
       [ 0.52686585,  1.26497721,  0.29905301,  0.81558314],
       [-0.5782994 , -0.86793028, -1.02028092, -1.35221332]])

In [135]:
data[data < 0] = 0 #0보다 작은거에 0 넣기!
data

array([[0.        , 0.        , 0.        , 0.90723345],
       [0.        , 0.        , 2.82136748, 0.        ],
       [0.45400475, 0.38930527, 0.37473453, 0.        ],
       [0.52686585, 1.26497721, 0.29905301, 0.81558314],
       [0.        , 0.        , 0.        , 0.        ],
       [0.22808906, 0.        , 0.33990549, 1.26991028],
       [0.        , 1.38626876, 0.        , 1.24760221]])

In [136]:
data[names != 'Joe'] = 7 # 조가 아닌거에 7넣기!
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 2.82136748, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.22808906, 0.        , 0.33990549, 1.26991028],
       [0.        , 1.38626876, 0.        , 1.24760221]])

### Transposing Arrays and Swapping Axes (배열 전치와 축 바꾸기)

In [138]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [139]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [140]:
arr = np.random.randn(6, 3)
arr

array([[ 0.93322094,  0.63997641, -0.95909571],
       [ 0.03624241, -0.87615818, -1.0926981 ],
       [-0.52372421,  0.79855842, -0.06631447],
       [-0.46360668,  0.66494141,  0.33678684],
       [ 1.86797714,  0.42833445, -0.80234045],
       [ 0.36556811,  0.12143076, -0.24813301]])

In [141]:
np.dot(arr.T, arr) # X^T*X는 np.dot로 구할수 있다.

array([[ 4.9844117 ,  0.68349983, -2.64551949],
       [ 0.68349983,  2.45528144,  0.14076425],
       [-2.64551949,  0.14076425,  2.93699689]])

In [150]:
arr = np.arange(16).reshape((2, 2, 4)) # 3차원2 * 2차원2 * 1차원4
print(arr)
print(arr.transpose((0, 1, 2))) # transpose 메소드는 튜플로 축번호를 받아서 치환

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [152]:
print(arr)
print(arr.swapaxes(1, 2)) # swapaxes 메소드: 2개의 축 번호를 받아서 배열을 바꾼다.

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


## Universal Functions: Fast Element-Wise Array Functions

In [ ]:
arr = np.arange(10) 
arr
np.sqrt(arr)

In [ ]:
x = np.random.randn(8)
y = np.random.randn(8)
x
y
np.maximum(x, y)

In [ ]:
arr = np.random.randn(7) * 5
arr
remainder, whole_part = np.modf(arr)
remainder
whole_part

In [ ]:
arr
np.sqrt(arr)
np.sqrt(arr, arr)
arr

### Expressing Conditional Logic as Array Operations

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [ ]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

In [ ]:
result = np.where(cond, xarr, yarr)
result

In [ ]:
arr = np.random.randn(4, 4)
arr
arr > 0
np.where(arr > 0, 2, -2)

In [ ]:
np.where(arr > 0, 2, arr) # set only positive values to 2

### Mathematical and Statistical Methods

In [ ]:
arr = np.random.randn(5, 4)
arr
arr.mean()
np.mean(arr)
arr.sum()

In [ ]:
arr.mean(axis=1)
arr.sum(axis=0)

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

In [ ]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr
arr.cumsum(axis=0)
arr.cumprod(axis=1)

### Methods for Boolean Arrays

In [ ]:
arr = np.random.randn(100)
(arr > 0).sum() # Number of positive values

In [ ]:
bools = np.array([False, False, True, False])
bools.any()
bools.all()

### Sorting

In [ ]:
arr = np.random.randn(6)
arr
arr.sort()
arr

In [ ]:
arr = np.random.randn(5, 3)
arr
arr.sort(1)
arr

In [ ]:
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))] # 5% quantile